const sizes = ['small', 'medium', 'large'];

const fileNames = [
  'image (1).jpeg',
  'image (1).jpg',
  'image (10).jpg',
  'image (100).jpg',
  'image (101).jpg',
  'image (102).jpg',
  'image (103).jpg',
  'image (104).jpg',
  'image (105).jpg',
  'image (106).jpg',
  'image (107).jpg',
  'image (108).jpg',
  'image (109).jpg',
  'image (11).jpg',
  'image (110).jpg',
  'image (111).jpg',
  'image (12).jpg',
  'image (13).jpg',
  'image (14).jpg',
  'image (15).jpg',
  'image (16).jpg',
  'image (17).jpg',
  'image (18).jpg',
  'image (19).jpg',
  'image (2).jpeg',
  'image (2).jpg',
  'image (20).jpg',
  'image (21).jpg',
  'image (22).jpg',
  'image (23).jpg',
  'image (24).jpg',
  'image (25).jpg',
  'image (26).jpg',
  'image (27).jpg',
  'image (28).jpg',
  'image (29).jpg',
  'image (3).jpeg',
  'image (3).jpg',
  'image (30).jpg',
  'image (31).jpg',
  'image (32).jpg',
  'image (33).jpg',
  'image (34).jpg',
  'image (35).jpg',
  'image (36).jpg',
  'image (37).jpg',
  'image (38).jpg',
  'image (39).jpg',
  'image (4).jpeg',
  'image (4).jpg',
  'image (40).jpg',
  'image (41).jpg',
  'image (42).jpg',
  'image (43).jpg',
  'image (44).jpg',
  'image (45).jpg',
  'image (46).jpg',
  'image (47).jpg',
  'image (48).jpg',
  'image (49).jpg',
  'image (5).jpeg',
  'image (5).jpg',
  'image (50).jpg',
  'image (51).jpg',
  'image (52).jpg',
  'image (53).jpg',
  'image (54).jpg',
  'image (55).jpg',
  'image (56).jpg',
  'image (57).jpg',
  'image (58).jpg',
  'image (59).jpg',
  'image (6).jpeg',
  'image (6).jpg',
  'image (60).jpg',
  'image (61).jpg',
  'image (62).jpg',
  'image (63).jpg',
  'image (64).jpg',
  'image (65).jpg',
  'image (66).jpg',
  'image (67).jpg',
  'image (68).jpg',
  'image (69).jpg',
  'image (7).jpeg',
  'image (7).jpg',
  'image (70).jpg',
  'image (71).jpg',
  'image (72).jpg',
  'image (73).jpg',
  'image (74).jpg',
  'image (75).jpg',
  'image (76).jpg',
  'image (77).jpg',
  'image (78).jpg',
  'image (79).jpg',
  'image (8).jpeg',
  'image (8).jpg',
  'image (80).jpg',
  'image (81).jpg',
  'image (82).jpg',
  'image (83).jpg',
  'image (84).jpg',
  'image (85).jpg',
  'image (86).jpg',
  'image (87).jpg',
  'image (88).jpg',
  'image (89).jpg',
  'image (9).jpg',
  'image (90).jpg',
  'image (91).jpg',
  'image (92).jpg',
  'image (93).jpg',
  'image (94).jpg',
  'image (95).jpg',
  'image (96).jpg',
  'image (97).jpg',
  'image (98).jpg',
  'image (99).jpg',
];

export default function RandomPin() {
  var random_pin = {
    author: 'Patryk',
    board: 'default',
    title: 'The Journey',
    description:
      'Embarking on a journey can be both exciting and daunting. The anticipation of new experiences and adventures can fill one with a sense of wonder and joy, while the uncertainty of the unknown can also bring feelings of anxiety and trepidation. Whether its a physical journey to a far-off destination or a personal journey of self-discovery, every journey has the potential to bring growth, learning, and meaningful insights into our lives.',
    destination: 'www.journey.com',
    pin_size: sizes[Math.floor(Math.random() * sizes.length)],
    img_blob: '/images/test pins/' + fileNames[Math.floor(Math.random() * fileNames.length)],
    // img_blob:'https://picsum.photos/400/600',
  };
  return random_pin;
}
